name: Build docker image

on:
  push:
    paths:
      - 'fastdeploy_recipe/requirements.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./fastdeploy_recipe/
        file: ./fastdeploy_recipe/fastDeploy.auto_dockerfile
        push: true
        tags: ghcr.io/graasp/nudenet:latest
